# Generated by Django 4.2.2 on 2023-08-12 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="business_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buss_fname", models.CharField(max_length=20)),
                ("buss_lname", models.CharField(max_length=20)),
                ("buss_emailid", models.CharField(max_length=40)),
                ("buss_password", models.CharField(max_length=30)),
                (
                    "buss_rpassword",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("buss_phonenum", models.CharField(blank=True, max_length=13)),
                (
                    "buss_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "buss_last_login",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("buss_auth_token", models.CharField(max_length=100, null=True)),
                ("buss_is_verified", models.BooleanField(default=False)),
                (
                    "buss_updProfile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="BussProfileImg/"
                    ),
                ),
                ("buss_role", models.CharField(max_length=30)),
                ("buss_status", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="buss_contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buss_name", models.CharField(max_length=30)),
                ("buss_email", models.CharField(max_length=30)),
                ("buss_phone", models.CharField(max_length=30)),
                ("buss_message", models.CharField(max_length=30)),
                ("buss_contact_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="buss_vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buss_vehicle_id", models.CharField(default="BUS1000", max_length=10)),
                (
                    "buss_vehicle_company_name",
                    models.CharField(
                        choices=[
                            ("Toyota", "Toyota"),
                            ("Honda", "Honda"),
                            ("Ford", "Ford"),
                            ("Chevrolet", "Chevrolet"),
                            ("Nissan", "Nissan"),
                            ("Volkswagen", "Volkswagen"),
                            ("BMW", "BMW"),
                            ("Mercedes-Benz", "Mercedes-Benz"),
                            ("Audi", "Audi"),
                            ("Hyundai", "Hyundai"),
                            ("Kia", "Kia"),
                            ("Subaru", "Subaru"),
                            ("Mazda", "Mazda"),
                            ("Lexus", "Lexus"),
                            ("Jeep", "Jeep"),
                            ("Chrysler", "Chrysler"),
                            ("Volvo", "Volvo"),
                            ("Porsche", "Porsche"),
                            ("Land Rover", "Land Rover"),
                            ("Tesla", "Tesla"),
                        ],
                        max_length=40,
                    ),
                ),
                ("buss_vehicle_model", models.CharField(max_length=50, null=True)),
                (
                    "buss_vehicle_color",
                    models.CharField(
                        choices=[
                            ("Black", "Black"),
                            ("White", "White"),
                            ("Silver", "Silver"),
                            ("Gray", "Gray"),
                            ("Red", "Red"),
                            ("Blue", "Blue"),
                            ("Green", "Green"),
                            ("Yellow", "Yellow"),
                            ("Orange", "Orange"),
                            ("Purple", "Purple"),
                            ("Brown", "Brown"),
                            ("Beige", "Beige"),
                            ("Gold", "Gold"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("buss_vehicle_number", models.CharField(max_length=40)),
                (
                    "buss_vehicle_type",
                    models.CharField(
                        choices=[
                            ("SUV", "SUV (Sports Utility Vehicle)"),
                            ("Sedan", "Sedan"),
                            ("Hatchback", "Hatchback"),
                            ("Convertible", "Convertible"),
                            ("Truck", "Truck"),
                            ("Van", "Van"),
                            ("Coupe", "Coupe"),
                            ("Crossover", "Crossover"),
                            ("Minivan", "Minivan"),
                            ("Pickup", "Pickup Truck"),
                            ("Wagon", "Wagon"),
                            ("Electric", "Electric Car"),
                            ("Luxury", "Luxury Car"),
                            ("Sports", "Sports Car"),
                            ("Hybrid", "Hybrid Car"),
                            ("Station_Wagon", "Station Wagon"),
                            ("Compact", "Compact Car"),
                            ("Muscle", "Muscle Car"),
                            ("Supercar", "Supercar"),
                            ("Classic", "Classic Car"),
                            ("Off_Road", "Off-Road Vehicle"),
                            ("Roadster", "Roadster"),
                            ("Limousine", "Limousine"),
                            ("Microcar", "Microcar"),
                            ("Subcompact", "Subcompact Car"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "buss_vehicle_location",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("buss_rent_per_day", models.CharField(max_length=40)),
                ("buss_vehicle_description", models.TextField()),
                ("buss_vehicle_is_verified", models.BooleanField(default=False)),
                ("buss_vehicle_is_soldout", models.BooleanField(default=False)),
                (
                    "buss_vehicle_status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Booked", "Booked"),
                            ("Rented", "Rented"),
                            ("Under Maintenance", "Under Maintenance"),
                            ("Out of Service", "Out of Service"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "buss_vehicle_photo",
                    models.ImageField(upload_to="rental_buss/added_vehicles/"),
                ),
                (
                    "buss_vehicle_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rental_business.business_user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="buss_feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buss_name", models.CharField(max_length=30)),
                ("buss_ratings", models.CharField(max_length=25)),
                ("buss_comments", models.CharField(max_length=50)),
                (
                    "buss_l_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rental_business.business_user",
                    ),
                ),
            ],
        ),
    ]
