# Generated by Django 4.2.2 on 2023-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buss_vehicle",
            name="buss_vehicle_status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Booked", "Booked"),
                    ("Under Maintenance", "Under Maintenance"),
                    ("Out of Service", "Out of Service"),
                ],
                max_length=20,
            ),
        ),
    ]
