# Generated by Django 5.0.6 on 2024-12-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_business', '0002_alter_buss_vehicle_buss_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buss_vehicle',
            name='buss_vehicle_company_name',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Mahindra', 'Mahindra'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Tata Motors', 'Tata Motors'), ('Nissan', 'Nissan'), ('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Subaru', 'Subaru'), ('Mazda', 'Mazda'), ('Lexus', 'Lexus'), ('Jeep', 'Jeep'), ('Chrysler', 'Chrysler'), ('Volvo', 'Volvo'), ('Porsche', 'Porsche'), ('Land Rover', 'Land Rover'), ('Tesla', 'Tesla'), ('MG Motors', 'MG Motors')], max_length=40),
        ),
    ]
