# Generated by Django 5.0.6 on 2024-12-20 20:01

import rental_business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_business', '0003_alter_buss_vehicle_buss_vehicle_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss_vehicle',
            name='buss_chassi_number',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[rental_business.models.buss_vehicle.validate_chassis_number]),
        ),
        migrations.AddField(
            model_name='buss_vehicle',
            name='buss_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buss_vehicle',
            name='buss_year_of_manufacture',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='buss_vehicle',
            name='buss_vehicle_company_name',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Mahindra', 'Mahindra'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Tata Motors', 'Tata Motors'), ('Nissan', 'Nissan'), ('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Suzuki', 'Suzuki'), ('Kia', 'Kia'), ('Subaru', 'Subaru'), ('Mazda', 'Mazda'), ('Lexus', 'Lexus'), ('Jeep', 'Jeep'), ('Chrysler', 'Chrysler'), ('Volvo', 'Volvo'), ('Porsche', 'Porsche'), ('Land Rover', 'Land Rover'), ('Tesla', 'Tesla'), ('MG Motors', 'MG Motors')], max_length=40),
        ),
    ]
