# Generated by Django 5.0.6 on 2024-12-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_business', '0004_buss_vehicle_buss_chassi_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_user',
            name='buss_aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business_user',
            name='buss_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business_user',
            name='buss_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business_user',
            name='buss_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business_user',
            name='buss_country',
            field=models.CharField(blank=True, default='India', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business_user',
            name='buss_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business_user',
            name='buss_driver_license_expiry',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='business_user',
            name='buss_driver_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business_user',
            name='buss_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business_user',
            name='buss_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
