# Generated by Django 4.2.2 on 2023-08-25 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rental_business", "0002_alter_buss_vehicle_buss_vehicle_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=30)),
                ("message", models.CharField(max_length=30)),
                ("contact_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="usertable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=20)),
                ("lname", models.CharField(max_length=20)),
                ("emailid", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=30)),
                ("rpassword", models.CharField(blank=True, max_length=30, null=True)),
                ("phonenum", models.CharField(blank=True, max_length=13)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_login", models.DateTimeField(default=django.utils.timezone.now)),
                ("auth_token", models.CharField(max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "updProfile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="UserProfileImg/"
                    ),
                ),
                ("role", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("ratings", models.CharField(max_length=25)),
                ("comments", models.CharField(max_length=50)),
                (
                    "l_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentalapp.usertable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="booking_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_duration", models.DateField()),
                ("from_to", models.DateField()),
                ("amount", models.CharField(max_length=30)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("paystatus", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentalapp.usertable",
                    ),
                ),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rental_business.buss_vehicle",
                    ),
                ),
            ],
        ),
    ]
