# Generated by Django 4.2.2 on 2023-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking_table",
            name="buss_vehicle_status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Booked", "Booked"),
                    ("Under Maintenance", "Under Maintenance"),
                    ("Out of Service", "Out of Service"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
