# Generated by Django 4.2.2 on 2023-08-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0002_booking_table_buss_vehicle_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking_table",
            name="buss_vehicle_status",
        ),
    ]
