# Generated by Django 4.2.2 on 2023-09-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_usertable_pass_reset_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='pass_reset_token',
            new_name='password_reset_token',
        ),
    ]
