# Generated by Django 4.2.2 on 2023-10-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0006_usertable_password_reset_token_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='password_reset_token_expiration_time',
            field=models.DateTimeField(null=True),
        ),
    ]
