# Generated by Django 4.2.2 on 2023-10-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0007_alter_usertable_password_reset_token_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='password_reset_token_expiration_time',
        ),
    ]
