# Generated by Django 4.2.2 on 2023-11-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0009_usertable_password_reset_token_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='rpassword',
        ),
    ]
