# Generated by Django 5.0.6 on 2024-07-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0010_remove_usertable_rpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
