# Generated by Django 5.0.6 on 2024-12-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0013_usertable_aadhaar_number_usertable_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='driver_license_expiry',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
