# Generated by Django 5.0.6 on 2025-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0014_booking_table_approval_date_booking_table_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('upi', 'UPI')], default='cash', max_length=20),
        ),
    ]
