# Generated by Django 5.0.6 on 2025-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0015_booking_table_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
    ]
